apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-gitops
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: clickhouse
      targetRevision: 16.x.x
      ref: helm-chart
    - repoURL: https://github.com/eomchanwoo/kubernetes-practice.git
      targetRevision: main
      ref: values
      helm:
        valueFiles:
          - $values/clickhouse/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse