shards: 1
replicaCount: 1

keeper:
  replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/clickhouse
  tag: 25.7.5-debian-12-r2

keeper:
  image:
    registry: docker.io
    repository: bitnami/clickhouse-keeper
    tag: 25.7.5-debian-12-r2